openapi: 3.0.3
info:
  title: 'HCPortal API'
  description: 'HCPortal - Ciphers and Cipher keys API documentation'
  version: 1.0.0
servers:
  -
    url: 'http://dp.test'
paths:
  /api/login:
    post:
      summary: Login
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 422
                  message: 'Validation errors'
                  data:
                    login: 'These credentials do not match our records.'
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: 'Validation errors'
                  data:
                    type: object
                    example:
                      login: 'These credentials do not match our records.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Login e-mail'
                  example: login@login.sk
                password:
                  type: string
                  description: Password
                  example: excepturi
              required:
                - email
                - password
      security: []
  /api/token/validation:
    get:
      summary: 'Check token'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 201
                  message: 'Token valid check.'
                  data: false
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: 'Token valid check.'
                  data:
                    type: boolean
                    example: false
      tags:
        - Authentication
  /api/logout:
    get:
      summary: 'Log out'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 200
                  message: 'Successfully logged out.'
                  data: null
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Successfully logged out.'
                  data:
                    type: string
                    example: null
      tags:
        - Authentication
  /api/register:
    post:
      summary: Register
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 422
                  message: 'Validation errors.'
                  data:
                    first_name:
                      - 'The first name field is required.'
                    last_name:
                      - 'The last name field is required.'
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: 'Validation errors.'
                  data:
                    type: object
                    example:
                      first_name:
                        - 'The first name field is required.'
                      last_name:
                        - 'The last name field is required.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: Firstname
                  example: est
                last_name:
                  type: string
                  description: Lastname
                  example: quo
                email:
                  type: string
                  description: 'Login e-mail'
                  example: login@login.sk
                password:
                  type: string
                  description: Password
                  example: eveniet
              required:
                - first_name
                - last_name
                - email
                - password
      security: []
  /api/password/reset/code:
    post:
      summary: 'Change password'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 422
                  message: 'Validation errors.'
                  data:
                    code:
                      - 'The code field is required.'
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: 'Validation errors.'
                  data:
                    type: object
                    example:
                      code:
                        - 'The code field is required.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Login e-mail'
                  example: login@login.sk
                code:
                  type: string
                  description: 'Password reset code'
                  example: alias
                password:
                  type: string
                  description: 'New password'
                  example: inventore
              required:
                - email
                - code
                - password
      security: []
  /api/password/reset:
    post:
      summary: 'Send forgot password code'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: Success
                  status_code: 422
                  message: 'Validation errors.'
                  data:
                    email:
                      - 'The email field is required.'
                properties:
                  status:
                    type: string
                    example: Success
                  status_code:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: 'Validation errors.'
                  data:
                    type: object
                    example:
                      email:
                        - 'The email field is required.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Login e-mail'
                  example: login@login.sk
              required:
                - email
      security: []
tags:
  -
    name: Authentication
    description: "\nAPIs for Auth"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
